---
## general network infrastructure services
domain_services:
  cobbler: cobbler.lab.rmkra.us
  freeipa: ipa.lab.rmkra.us
  unifi: ubnt.home.rmkra.us:8443
unifi_usergroup: 'Lab'
dns_records_primary_forward_zone: 'lab.rmkra.us'
dns_records_primary_reverse_zone: '4.168.192.in-addr.arpa'
ipa_client_install_flags: '--mkhomedir --no-sshd --no-ntp --force-join'

## Lynis Security Scanning configuration
lynis_global_exceptions:
  - BOOT-5122  # Home lab, GRUB passwords probably aren't necessary
  - FINT-4350  # I don't think I need to run AIDE at home
  - FIRE-4513  # Default firewall rules are fine, ansible gets the rest
  - HRDN-7222  # Compilers are managed by rpms and used for installs
  - HRDN-7230  # I don't want to manage malware scanners at the moment
  - NAME-4404  # The default /etc/hosts file is fine
  - NETW-2705  # Home network, 1 DNS server is fine
  - NETW-3032  # Home network, I don't really want arpwatch logging
  - SSH-7408:loglevel  # Verbose logging is a bit much
  - SSH-7408:port  # Let's keep SSH on port 22
  - STRG-1846  # I'm not familiar with disabling firmware storage
lynis_os_exceptions:
  Fedora:
    '29': []
  RedHat:
    '6':
      - AUTH-9308  # Home lab, I don't want a single user password
      - SSH-7408:useprivilegeseparation  # sandbox is not an option here
    '7': []
  CentOS:
    '6':
      - AUTH-9308  # Home lab, I don't want a single user password
      - SSH-7408:useprivilegeseparation  # sandbox is not an option here
    '7': []

## General System Configuration
ntp_servers:
  - gateway.home.rmkra.us
postfix_mynetworks: 192.168.0.0/16
postfix_myorigin: rmkra.us
postfix_relayhost: "lab.rmkra.us"
rhsm:
  username: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31323539356362616166643163643035353836316238333466316462643432336663393338313630
          3066323266393166326262373733303164333839386232630a663762326662363961613630663833
          61393961356330623333613236393333613036303232396431366433306561323563303262393239
          6264393362323738310a356336653638623661643032613431383465323061643936343038363964
          36666563646264646338643832623434363362626535356133393332343738363064
  password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35623535373135363263616537653939303639333939343666616462653962316561346232363030
          3339383030353965393433396636343763626562306533340a663832653764626534343531396661
          31643034643863313835306631633930666661386138343030613738663437613361326230396636
          3937306566306566370a633537343461366634636534366337663432653265323439303834303237
          6163
  pools:
    - 8a85f98460bfb0470160c2ff22f13e47
root_user_password_crypted: "{{ lookup('lastpass', 'root', field='encrypted') }}"
root_user_ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCyEmE9RgpVOEfrTih/aw7eF9r44YPYIJgqkFOkREDxSzh9T580vee5LI5NdgD8+dIFPVHjzeOGYqHudQjwPDuPNCqaYZg3+AT1+4uHeiAyQ4OvS5dLeHU4K9fX8FBCnFOpxde6rBlSnEF3+ZuMdiQAVmNPD50XmYnbohUHh+3vVam9stNAN6iZw1OWz7Q5JxDYayjyk1htAH20f0OaKR0e9xCDS4B1e+qJjUN7ZSVyAV95ojzP5NPkk0ImQhvH+rnRepPp3LYrst9CYIboH0sVU++y0zubO0wWZ5XXRmlF7qmm6Q+MKGVwO8AjCY+kRCpWB+hEkKnG85pyPsh8myHt root@lab.rmkra.us
ssh_banner: |
    ********************************************************************
    *                  _                                               *
    *                 | |                                              *
    * _ __  _ __ ___  | | __ _ __  __ _    _   _  ___                  *
    *| '__|| '_ ` _ \ | |/ /| '__|/ _` |  | | | |/ __|                 *
    *| |   | | | | | ||   < | |  | (_| |  | |_| |\__ \                 *
    *|_|   |_| |_| |_||_|\_\|_|   \__,_|(*)\__,_||___/******************
    *                                                                  *
    * This system is for the use of authorized users only.  Usage of   *
    * this system may be monitored and recorded by system personnel.   *
    *                                                                  *
    * Anyone using this system expressly consents to such monitoring   *
    * and is advised that if such monitoring reveals possible          *
    * evidence of criminal activity, system personnel may provide the  *
    * evidence from such monitoring to law enforcement officials.      *
    *                                                                  *
    ********************************************************************
