rhsm_repos:
  - name: rhel-7-server-rhvh-4-rpms
monitoring: no
disks:
  - device: /dev/sda
    partitions:
      - id: 4
        name: var_www_cobbler
        start: 50GB
        end: 1000GB
        unit: GB
        type: extended
      - id: 5
        name: var_www_cobbler
        start: 50GB
        end: 125GB
        unit: GB
        type: logical
      - id: 6
        name: downloads
        start: 125GB
        end: 1000GB
        unit: GB
        type: logical
dns_records_custom_records:
  - name: rhv
    type: A
    value: 192.168.4.200
    zone: lab.rmkra.us
  - name: '200'
    type: PTR
    value: rhv.lab.rmkra.us.
    zone: '4.168.192.in-addr.arpa'
