rhsm_repos:
  - name: rhel-7-server-ansible-2.7-rpms
  - name: rhel-7-server-extras-rpms
disks:
  - device: /dev/sdb
    partitions:
      - id: 1
        name: postgres
        start: '0%'
        end: '100%'
        unit: '%'
        fstype: xfs
        mount: /var/lib/pgsql
tower_admin_password: "{{ lookup('lastpass', 'root', field='encrypted') }}"
tower_pg_password: "{{ lookup('lastpass', 'Tower', field='pg_password') }}"
tower_rabbitmq_password: "{{ lookup('lastpass', 'Tower', field='rabbitmq_password') }}"

tower_ssl_cert: "{{ lookup('lastpass', 'Certs/tower.lab.rmkra.us', field='cert') }}"
tower_ssl_key: "{{ lookup('lastpass', 'Certs/tower.lab.rmkra.us', field='privkey') }}"
tower_custom_cert: yes

hardening_default_umask: "022"
