rhsm_repos:
  - name: rhel-7-server-ansible-2.7-rpms
  - name: rhel-7-server-extras-rpms
disks:
  - device: /dev/sdb
    partitions:
      - id: 1
        name: postgres
        start: '0%'
        end: '100%'
        unit: '%'
tower_admin_password: "{{ lookup('lastpass', 'root', field='encrypted') }}"
tower_pg_password: "{{ lookup('lastpass', 'Tower', field='pg_password') }}"
tower_rabbitmq_password: "{{ lookup('lastpass', 'Tower', field='rabbitmq_password') }}"

tower_ssl_cert: '/ansible_vault/ssl_certs/config/live/tower.lab.rmkra.us/cert.pem'
tower_ssl_key: '/ansible_vault/ssl_certs/config/live/tower.lab.rmkra.us/privkey.pem'
tower_custom_cert: yes
