cobbler_ssl_cert: /ansible_vault/ssl_certs/config/live/cobbler.lab.rmkra.us/cert.pem
cobbler_ssl_key: /ansible_vault/ssl_certs/config/live/cobbler.lab.rmkra.us/privkey.pem
cobbler_ssl_chain: /ansible_vault/ssl_certs/config/live/cobbler.lab.rmkra.us/chain.pem
disks:
  - device: /dev/sda
    partitions:
      - id: 1
        name: var_www_cobbler
        start: 0%
        end: 50%
        fstype: xfs
        mount: /var/www/cobbler
      - id: 2
        name: downloads
        start: 50%
        end: 100%
        fstype: xfs
        mount: /downloads
lynis_host_exceptions:
  - FILE-6310  # Cannot easily control partition tables on a pi
  - FILE-6336  # Cannot easily control partition tables on a pi
hardening_selinux: disabled
