cobbler_ssl_cert: "{{ lookup('lastpass', 'Certs/cobbler.lab.rmkra.us', field='cert') }}"
cobbler_ssl_key: "{{ lookup('lastpass', 'Certs/cobbler.lab.rmkra.us', field='privkey') }}"
cobbler_ssl_chain: "{{ lookup('lastpass', 'Certs/cobbler.lab.rmkra.us', field='chain') }}"
disks:
  - device: /dev/sda
    partitions:
      - id: 1
        name: var_www_cobbler
        start: 0%
        end: 50%
        fstype: xfs
        mount: /var/www/cobbler
      - id: 2
        name: downloads
        start: 50%
        end: 100%
        fstype: xfs
        mount: /downloads
lynis_host_exceptions:
  - FILE-6310  # Cannot easily control partition tables on a pi
  - FILE-6336  # Cannot easily control partition tables on a pi
hardening_selinux: disabled
