rhsm_repos:
  - name: rhel-7-server-rpms
  - name: rhel-7-server-supplementary-rpms
  - name: rhel-7-server-rhv-4.2-manager-rpms
  - name: rhel-7-server-rhv-4-manager-tools-rpms
  - name: rhel-7-server-ansible-2-rpms
  - name: jb-eap-7-for-rhel-7-server-rpms
