#!/usr/bin/ansible-playbook
---
- name: Connect to Secret Stores
  hosts: all
  gather_facts: no
  become: no
  tags: 'secrets'

  vars_prompt:
  - name: "lastpass_username"
    prompt: "LastPass Username"
    private: no
  - name: "lastpass_password"
    prompt: "LastPass Master Password"
    private: yes

  roles:
    - lastpass

  tasks:
    - name: import secrets.yml
      include_vars:
        file: secrets.yml
        name: secrets
