#!/usr/bin/ansible-playbook
---

- name: get host information from switch
  hosts: all:!macs

  roles:
    - role: unifi
      unifi_action: login
      unifi_server: "{{ domain_services.unifi.server }}"
      unifi_user: "{{ domain_services.unifi.user }}"
      unifi_pass: "{{ domain_services.unifi.password }}"
    - role: unifi
      unifi_action: logout
      unifi_server: "{{ domain_services.unifi.server }}"
      tags:
        - dhcp

- name: core configuration to all hosts
  hosts: all:!macs
  become: yes
  become_user: root

  roles:
    - dns_records
    - ansible-deps
    - root-user
    - lynis
    - ntp
    - ssh
    - hardening
    - monitoring
    - filesystem

- name: pxe boot/dhcp server
  hosts: pxe_server
  become: yes
  become_user: root

  roles:
    - disks
    - epel
    - cobbler

- name: production infra nodes
  hosts: infra
  become: yes
  become_user: root

  roles:
    - bind

- name: static docker hosts
  hosts: docker
  become: yes
  become_user: root

  roles:
    - docker
...
