#!/usr/bin/ansible-playbook
---

- name: get host information from switch
  hosts: all:!macs:!networking

  roles:
    - role: unifi
      unifi_action: login
      unifi_server: "{{ domain_services.unifi.server }}"
      unifi_user: "{{ domain_services.unifi.user }}"
      unifi_pass: "{{ domain_services.unifi.password }}"
      tags:
        - dns_records
        - dns
        - dhcp

    - role: unifi
      unifi_action: logout
      unifi_server: "{{ domain_services.unifi.server }}"
      tags:
        - dns_records
        - dns
        - dhcp

- name: core configuration to all hosts
  hosts: all:!macs:!networking
  become: yes
  become_user: root

  roles:
    - rhsm
    - dns_records
    - ansible-deps
    - root-user
    - lynis
    - ntp
    - hardening
    - monitoring
    - filesystem
    - postfix
    - role: ipa-client
      ipa_client_principal: "{{ domain_services.freeipa.user }}"
      ipa_client_pass: "{{ domain_services.freeipa.password }}"
    - ssh

- name: pxe boot/dhcp server
  hosts: pxe_server
  become: yes
  become_user: root

  roles:
    - disks
    - epel
    - cobbler

- name: production infra nodes
  hosts: infra
  become: yes
  become_user: root

  roles:
    - bind
    - vip

- name: static docker hosts
  hosts: docker
  become: yes
  become_user: root

  roles:
    - docker

- name: configure Red Hat IdM servers
  hosts: rhidm
  become: yes
  become_user: root

  roles:
    - ipa-server
...
