#!/usr/bin/ansible-playbook
---

- name: connect to secret stores
  import_playbook: load_secrets.yml

- name: remove server from the network
  hosts: "{{ stat_limit|default('all') }}"
  gather_facts: no

  roles:
    - role: unifi
      unifi_action: login
      unifi_server: "{{ domain_services.unifi }}"
      unifi_user: "{{ secrets.ansible_account }}"
      unifi_pass: "{{ secrets.ansible_password }}"
      tags:
        - dhcp

    - role: dns_records
      dns_records_host: "{{ domain_services.freeipa }}"
      dns_records_user: "{{ secrets.ansible_account }}"
      dns_records_password: "{{ secrets.ansible_password }}"
      dns_records_state: absent
      dns_records_set_local: no
      tags:
        - dns

    - role: pxe_boot
      pxe_boot_action: remove
      pxe_boot_server: "{{ domain_services.cobbler }}"
      pxe_boot_user: "{{ secrets.ansible_account }}"
      pxe_boot_password: "{{ secrets.ansible_password }}"
      tags:
        - pxe

    - role: unifi
      unifi_action: forget
      unifi_server: "{{ domain_services.unifi }}"
      tags:
        - dhcp

    - role: unifi
      unifi_action: logout
      unifi_server: "{{ domain_services.unifi }}"
      tags:
        - dhcp

    - role: ipa-client
      ipa_client_action: remove
      ipa_client_principal: "{{ secrets.ansible_account }}"
      ipa_client_pass: "{{ secrets.ansible_password }}"
      ipa_client_host: "{{ domain_services.freeipa }}"
