- name: Workstation Setup
  hosts: none
  become: true

  vars:
    docker_users:
      - rkraus

  roles:
    - name: common
    - name: desktop-tools
    - name: nvidia-driver
    - name: google-chrome
    - name: vscode
    - name: golang
    - name: awscli
    - name: gcloud-cli
    - name: docker
    - name: python
    - name: sunshine-streaming
      sunshine_user: root
