- name: Workstation Setup
  hosts: dsws
  become: true

  roles:
    - name: common
    - name: desktop-tools
    - name: nvidia-driver
    - name: google-chrome
    - name: vscode
    - name: golang
    - name: awscli
    - name: gcloud-cli
    - name: docker
