---
# tasks file for rhsm
- name: ensure red hat systems are have subscription
  redhat_subscription:
    state: present
    username: "{{ rhsm.username }}"
    password: "{{ rhsm.password }}"
    pool_ids: "{{ rhsm.pools }}"
  when:
    - ansible_distribution == 'RedHat'
  tags:
    - rhsm

- name: ensure repositories are properly set
  rhsm_repository:
    name: '{{ item.name }}'
    state: '{{ item.state | default("enabled") }}'
  loop: "{{ rhsm_repos }}"
  tags:
    - rhsm
