---
# tasks file for pxe_boot
- name: ensure host does not exist in cobbler
  cobbler_system:
    host: "{{ domain_services.cobbler.server }}"
    username: "{{ domain_services.cobbler.user }}"
    password: "{{ domain_services.cobbler.password }}"
    name: "{{ inventory_hostname }}"
    use_ssl: yes
    state: absent
  delegate_to: localhost
  notify: cobbler sync
  tags:
    - pxe_boot
