---
# tasks file for pxe_boot
- name: ensure cobbler will pxe boot the host
  cobbler_system:
    host: "{{ pxe_boot_server }}"
    username: "{{ pxe_boot_user }}"
    password: "{{ pxe_boot_password }}"
    name: "{{ inventory_hostname }}"
    use_ssl: yes
    properties:
      netboot_enabled: "{{ pxe_boot_netboot }}"
      status: production
      hostname: "{{ inventory_hostname }}"
      profile: "{{ pxe_profile }}"
    interfaces:
      primary:
        macaddress: "{{ mac_address }}"
        dhcptag: "default"
  delegate_to: localhost
  notify: cobbler sync
  tags:
    - pxe_boot
