---
# tasks file for vscode
- name: ensure vscode repo is configured
  ansible.builtin.yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: true
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: install vscode
  ansible.builtin.package:
    name:
      - code
