- name: insert custom defined records
  ipa_dnsrecord:
    ipa_user: '{{ dns_records_user }}'
    ipa_host: '{{ dns_records_host.split(":").0 }}'
    ipa_pass: '{{ dns_records_password }}'
    validate_certs: no
    state: '{% if dns_records_state == "present" %}{{ item.state | default("present") }}{% else %}{{ dns_records_state }}{% endif %}'
    zone_name: '{{ item.zone }}'
    record_name: "{{ item.name }}"
    record_type: "{{ item.type | default('A') }}"
    record_value: "{{ item.value | default(unifi_ip) }}"
    record_ttl: 300
  delegate_to: localhost
  become: no
  loop: '{{ dns_records_custom_records }}'
  loop_control:
    label: "{{ item.name }}"
  when:
    - unifi_ip is not undefined
  register: dns
  failed_when: 'not ( dns.changed or dns.msg == "response dnsrecord_mod: no modifications to be performed" )'
  tags:
    - dns_records
    - dns
