---
# tasks file for dns_records
- name: set primary dns forward record
  nsupdate:
    server: "{{ domain_services.dns.server }}"
    record: "{{ inventory_hostname | replace('.' + dns_records_primary_forward_zone, '') }}"
    type: "A"
    value: "{{ unifi_ip }}"
    key_algorithm: "{{ domain_services.dns.algorithm }}"
    key_secret: "{{ domain_services.dns.secret }}"
    key_name: '{{ domain_services.dns.key_name'
    zone: '{{ dns_records_primary_forward_zone }}'
    state: present
  when:
    - unifi_ip is not undefined
  tags:
    - dns_records
    - dns

- name: determine reverse record name - step 1
  set_fact:
    unifi_ip_split: "{{ unifi_ip | split('.') }}"
  when:
    - unifi_ip is not undefined
  tags:
    - dns_records
    - dns

- name: determine reverse record name - step 2
  set_fact:
    dns_records_reverse: "{{ unifi_ip_split.3 + '.' + unifi_ip_split.2 + '.' + unifi_ip_split.1 + '.' + unifi_ip_split.0 + '.in-addr.arpa' }}"
  when:
    - unifi_ip is not undefined

- debug:
    msg: "{{ dns_records_reverse }}"
