- include_tasks: primary_records.yml
  tags:
    - dns_records
    - dns

- include_tasks: extra_records.yml
  tags:
    - dns_records
    - dns

- name: ensure hostname is set
  hostname:
    name: "{{ inventory_hostname }}"
  when: dns_records_set_local
  tags:
    - dns_records
    - hostname
