---
# tasks file for dns_records
- name: set primary dns forward record
  ipa_dnsrecord:
    ipa_user: '{{ dns_records_user }}'
    ipa_host: '{{ dns_records_host.split(":").0 }}'
    ipa_pass: '{{ dns_records_password }}'
    validate_certs: no
    state: "{{ dns_records_state }}"
    zone_name: '{{ dns_records_primary_forward_zone }}'
    record_name: "{{ inventory_hostname.split('.').0 }}"
    record_type: "A"
    record_value: "{{ unifi_ip | default('') }}"
    record_ttl: 300
  delegate_to: localhost
  become: no
  when:
    - unifi_ip is not undefined or dns_records_state == 'absent'
  register: dns
  failed_when:
    - 'not (dns.msg is undefined and dns_records_state == "absent")'
    - 'not dns.changed'
    - 'dns.msg|default("") != "response dnsrecord_mod: no modifications to be performed" )'
  tags:
    - dns_records
    - dns

- name: determine reverse record name
  set_fact:
    dns_records_reverse: "{{ unifi_ip.split('.').3 + '.' + unifi_ip.split('.').2 + '.' + unifi_ip.split('.').1 + '.' + unifi_ip.split('.').0 + '.in-addr.arpa' }}"
  delegate_to: localhost
  become: no
  when:
    - unifi_ip is not undefined
    - unifi_ip  != ''
  tags:
    - dns_records
    - dns

- name: set primary dns reverse record
  ipa_dnsrecord:
    ipa_user: '{{ dns_records_user }}'
    ipa_host: '{{ dns_records_host.split(":").0 }}'
    ipa_pass: '{{ dns_records_password }}'
    validate_certs: no
    state: "{{ dns_records_state }}"
    zone_name: '{{ dns_records_primary_reverse_zone }}'
    record_name: "{{ dns_records_reverse | replace('.' + dns_records_primary_reverse_zone, '') }}"
    record_type: "PTR"
    record_value: "{{ inventory_hostname.split('.').0 + '.' + dns_records_primary_forward_zone }}."
    record_ttl: 300
  delegate_to: localhost
  become: no
  when:
    - unifi_ip is not undefined
    - unifi_ip  != ''
  register: dns
  failed_when:
    - 'not (dns.msg is undefined and dns_records_state == "absent")'
    - 'not dns.changed'
    - 'dns.msg|default("") != "response dnsrecord_mod: no modifications to be performed" )'
  tags:
    - dns_records
    - dns
