---
# tasks file for monitoring
- name: Ensure monitoring tools are installed
  yum:
    name:
      - psacct
      - sysstat
    state: installed
  when: monitoring
  tags:
    - monitoring
    - packages

- name: Ensure monitoring is running
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - psacct
    - sysstat
  when: monitoring
  tags:
    - monitoring
    - services


