[DEFAULT]
{% if fail2ban_bantime is defined %}
bantime = {{ fail2ban_bantime }}
{% endif %}
banaction = iptables-multiport
{% if fail2ban_ignoreip is defined %}
ignoreip = {{ fail2ban_ignoreip }}
{% endif %}

{% for jail in fail2ban_jails %}
[{{ jail }}]
enabled = true

{% endfor %}
