---
- name: forget the host
  uri:
    url: https://{{ unifi_server }}/api/s/{{ unifi_site }}/cmd/stamgr
    method: POST
    validate_certs: no
    headers:
      Cookie: "{{ unifi_session }}"
    body:
      cmd: "forget-sta"
      macs:
        - "{{ mac_address }}"
    body_format: json
  register: unifi_action
  changed_when: unifi_action.status == 200
  delegate_to: localhost
  tags:
    - ubnt
    - unifi

- name: update unifi meta data
  set_fact:
    unifi_ip: ""
    unifi_host_id: ""
    unifi_network_id: ""
    unifi_ip_type: ""
  delegate_to: localhost
  tags:
    - ubnt
    - unifi
