---
- name: set unifi user group
  uri:
    url: https://{{ unifi_server }}/api/s/{{ unifi_site }}/rest/user/{{ unifi.host_id }}
    method: PUT
    validate_certs: no
    headers:
      Cookie: "{{ unifi_session }}"
    body:
      usergroup_id: '{{ unifi_usergroups[usergroup] }}'
    body_format: json
  when: "unifi_usergroup_id != unifi_usergroups[usergroup]"
  changed_when: unifi_action.status == 200
  delegate_to: localhost
  tags:
    - ubnt
    - unifi

- name: update unifi meta data
  set_fact:
    unifi_usergroup_id: '{{ unifi_usergroups[usergroup] }}'
  delegate_to: localhost
  tags:
    - ubnt
    - unifi

