---
- name: install development dependencies (1)
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - curl
    - make
    - wget
    - yum-utils
    - autoconf
    - bluez-libs
    - bluez-libs-devel
    - bzip2
    - bzip2-devel
    - cpp
    - expat-devel
    - fontconfig
    - fontconfig-devel
    - fontpackages-filesystem
    - freetype-devel
    - gcc
    - gcc-c++
    - gdbm-devel
    - glibc-devel
    - glibc-headers
    - gl-manpages
    - gmp-devel
    - kernel-headers
    - keyutils-libs-devel
    - krb5-devel
    - libcom_err-devel
    - libdb-devel
    - libdrm-devel
    - libffi-devel
    - libkadm5
    - libmpc
    - libselinux-devel
    - libsepol-devel
    - libstdc++-devel
    - libverto-devel
    - libX11
    - libX11-common
    - libX11-devel
    - libXau
    - libXau-devel
    - libxcb
  tags:
    - development
    - packages

- name: install development dependencies (2)
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - libxcb-devel
    - libXdamage
    - libXdamage-devel
    - libXext
    - libXext-devel
    - libXfixes
    - libXfixes-devel
    - libXft
    - libXft-devel
    - libXrender
    - libXrender-devel
    - libxshmfence
    - libXxf86vm
    - libXxf86vm-devel
    - lyx-fonts
    - m4
    - mesa-libGL
    - mesa-libglapi
    - mesa-libGL-devel
    - mpfr
    - ncurses-devel
    - openssl-devel
    - pcre-devel
    - perl-Data-Dumper
    - pyparsing
    - readline-devel
    - sqlite-devel
    - systemtap-sdt-devel
    - tcl
    - tcl-devel
    - tix
    - tix-devel
    - tk
    - tk-devel
    - valgrind
    - valgrind-devel
    - xorg-x11-proto-devel
    - zlib-devel
  tags:
    - development
    - packages
