---
# tasks file for root-user
- name: Ensure root's ssh directory exists
  file:
    dest: /root/.ssh
    owner: root
    group: root
    mode: 0700
    state: directory
  tags:
    - root-user
    - config

- name: Ensure root has a configured profile
  template:
    src: "{{ item }}.j2"
    dest: "/root/.ssh/.{{ item }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - bashrc
    - bash_profile
  tags:
    - root-user
    - config

- name: Ensure root has configured public ssh keys
  template:
    src: "authorized_keys.j2"
    dest: /root/.ssh/authorized_keys
    owner: root
    group: root
    mode: 0600
  tags:
    - root-user
    - config

- name: Ensure the root password has been set
  user:
    name: root
    password: "{{ root_user_password }}"
  tags:
    - root-user
    - config
    - root-password
