---
- name: ensure fail2ban is installed
  yum:
    name: fail2ban
    state: installed
  tags:
    - fail2ban

- name: ensure fail2ban is configured
  template:
    src: 99-ansible.conf
    dest: /etc/fail2ban/jail.d/99-ansible.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart fail2ban
  tags:
    - fail2ban

- name: ensure fail2ban is running and enabled
  service:
    name: fail2ban
    state: started
    enabled: yes
  tags:
    - fail2ban
