---
# tasks file for common
- name: allow wheel to sudo without password
  community.general.sudoers:
    name: "nopasswd wheel sudo"
    state: present
    group: wheel
    runas: root
    commands: ALL
    nopassword: true

- name: install common packages
  ansible.builtin.package:
    name:
      - vim

- name: ensure sshd is enabled
  ansible.builtin.service:
    name: sshd
    enabled: yes
    state: started

- name: ensure config sync is scheduled
  ansible.builtin.cron:
    name: configuration check
    special_time: "{{ item }}"
    job: /usr/bin/ansible-pull -U https://github.com/rmkraus/ansible.git site.yaml -i inventory.ini > /var/log/config_check
  with_items:
    - reboot
    - daily

- name: ensure patching is scheduled
  ansible.builtin.cron:
    name: system patching
    special_time: weekly
    job: /usr/bin/ansible-pull -U https://github.com/rmkraus/ansible.git patching.yaml -i inventory.ini > /var/log/config_check
