---
# tasks file for docker
- name: remove podman
  ansible.builtin.package:
    name:
      - podman
      - podman-docker
    state: absent

- name: install docker
  ansible.builtin.package:
    name:
      - docker-distribution
      - docker-compose

- name: enabled docker daemon
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started