#!/usr/bin/env -S ansible-playbook --ask-pass --user=root
---

- name: join server to network
  hosts: all
  become_user: root
  gather_facts: false

  vars:
    provisioning_profile: ""
    provisioning_image: "dummy"
    original_host: "{{ ansible_host }}"

  tasks:
    - name: find current IP address
      shell: arp -a | grep {{ mac_address }} | awk -F'[()]' '{print $2}'
      register: arp_lkp
      delegate_to: cobbler
      ignore_errors: yes

    - name: "discovered ip"
      debug:
        msg: "{{ arp_lkp.stdout_lines.0 }}"
      when: "arp_lkp.stdout_lines | length > 0"

    - name: create cobbler record
      cobbler_system:
        host: "{{ cobbler_server }}"
        username: "{{ cobbler_user }}"
        password: "{{ cobbler_password }}"
        name: "{{ inventory_hostname }}.{{ domain }}"
        use_ssl: yes
        properties:
          netboot_enabled: yes
          status: production
          hostname: "{{ inventory_hostname }}.{{ domain }}"
          profile: "{{ provisioning_profile }}"
          image: "{{ provisioning_image }}"
        interfaces:
          primary:
            macaddress: "{{ mac_address }}"
            ipaddress: "{{ original_host }}"
            dnsname: "{{ inventory_hostname }}.{{ domain }}"
            dhcptag: "default"
      delegate_to: localhost
      notify: cobbler sync

    - name: connect to host on old ip address
      set_fact:
        ansible_host: "{{ arp_lkp.stdout_lines.0 }}"
      when: "arp_lkp.stdout_lines | length > 0"

    - name: reboot the host
      command: shutdown -r now
      when: "arp_lkp.stdout_lines | length > 0"
      ignore_errors: yes

    - name: connect to host on new ip address
      set_fact:
        ansible_host: "{{ original_host }}"
      when: "arp_lkp.stdout_lines | length > 0"

    - name: wait for host to come up
      wait_for_connection:
        delay: 10

  handlers:
    - name: cobbler sync
      cobbler_sync:
        host: "{{ cobbler_server }}"
        username: "{{ cobbler_user }}"
        password: "{{ cobbler_password }}"
        use_ssl: yes
      delegate_to: localhost


...
