#!/usr/bin/ansible-playbook
---
- name: join server to the network
  hosts: all
  gather_facts: no

  roles:
    - role: unifi
      unifi_action: login
      unifi_server: "{{ domain_services.unifi.server }}"
      unifi_user: "{{ domain_services.unifi.user }}"
      unifi_pass: "{{ domain_services.unifi.password }}"
      tags:
        - dhcp

    - role: dns_records
      dns_records_state: absent
      dns_records_set_local: no
      tags:
        - dns

    - role: pxe_boot
      pxe_boot_action: remove
      tags:
        - pxe

    - role: unifi
      unifi_action: forget
      unifi_server: "{{ domain_services.unifi.server }}"
      tags:
        - dhcp

    - role: unifi
      unifi_action: logout
      unifi_server: "{{ domain_services.unifi.server }}"
      tags:
        - dhcp
