#!/usr/bin/ansible-playbook
# more api documentation here:
#   https://ubntwiki.com/products/software/unifi-controller/api
---
- name: test unifi api
  hosts: localhost
  gather_facts: no

  vars:
    unifi_user: service-ansible
    unifi_pass: 2468-Automate
    unifi_host: ubnt.home.rmkra.us:8443
    unifi_site: default
    mac_address: ac:1f:6b:73:2d:24
    host_nickname: host-2

  tasks:
    - name: login
      uri:
        url: https://{{ unifi_host }}/api/login
        method: POST
        validate_certs: no
        body:
          username: "{{ unifi_user }}"
          password: "{{ unifi_pass }}"
          remember: false
          strict: false
        body_format: json
      register: unifi_login

    - debug:
        msg: "{{ unifi_login }}"
        verbosity: 1

    - name: get host id
      uri:
        url: https://{{ unifi_host }}/api/s/{{ unifi_site }}/stat/user/{{ mac_address }}
        method: GET
        validate_certs: no
        headers:
          Cookie: "{{ unifi_login.set_cookie }}"
      register: unifi_meta
      ignore_errors: yes

    - debug:
        msg: "{{ unifi_meta }}"
        verbosity: 1

    - name: set host ip
      uri:
        url: https://{{ unifi_host }}/api/s/{{ unifi_site }}/rest/user/{{ unifi_meta.json.data.0._id }}
        method: PUT
        validate_certs: no
        headers:
          Cookie: "{{ unifi_login.set_cookie }}"
        body:
          name: "{{ host_nickname }}"
          fixed_ip: "{{ unifi_meta.json.data.0.ip }}"
          network_id: "{{ unifi_meta.json.data.0.network_id }}"
          use_fixedip: true
        body_format: json
      when: "'fixed_ip' not in unifi_meta.json.data.0 or 'name' not in unifi_meta.json.data.0 or host_nickname != unifi_meta.json.data.0.name"
      register: unifi_action
      changed_when: unifi_action.status == 200

    - debug:
        msg: "{{ unifi_action }}"
        verbosity: 1

    - name: logout
      uri:
        url: https://{{ unifi_host }}/api/logout
        method: POST
        validate_certs: no
        headers:
          Cookie: "{{ unifi_login.set_cookie }}"

