---
- name: ensure authenticator is installed
  yum:
    name: google-authenticator
    state: installed
  tags: mfa

- name: ensure mfa is enabled for sshd
  lineinfile:
    line: "{{ item.line }}"
    dest: "{{ item.dest }}"
    regexp: "{{ item.regexp }}"
  with_items:
    - { line: "PasswordAuthentication yes", dest: "/etc/ssh/sshd_config", regexp: "^PasswordAuthentication" }
    - { line: "UsePAM yes", dest: "/etc/ssh/sshd_config", regexp: "^UsePAM" }
    - { line: "auth required pam_google_authenticator.so nullok", dest: "/etc/pam.d/sshd", regexp: "^auth required pam_google_authenticator.so" }
    - { line: "ChallengeResponseAuthentication yes", dest: "/etc/ssh/sshd_config", regexp: "^ChallengeResponseAuthentication" }
  notify: restart sshd
  tags: mfa

- name: ensure mfa key generator is installed
  copy:
    src: mfa-check.sh
    dest: /usr/local/sbin/mfa-check.sh
    mode: 0755
    owner: root
    group: root
  tags:
    - mfa

- name: ensure key usage is enforced
  file:
    src: /usr/local/sbin/mfa-check.sh
    dest: /etc/profile.d/mfa-check.sh
    state: link
  tags: mfa
