---
- name: ensure ssh server is configured
  lineinfile:
    line: "PermitRootLogin without-password"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0600"
  notify: restart ssh
  tags: ssh
